# ==================== BLOCKCHAIN - SEPOLIA (OFFICIAL HACKATHON) ====================
#web3j.endpoint=https://rpc.sepolia.org
web3j.endpoint=https://eth-sepolia.g.alchemy.com/v2/7oe-KgpcszHwQWfpPgrSh

# === OFFICIAL SHARED CONTRACTS ===
contract.identity=0x97b07dDc405B0c28B17559aFFE63BdB3632d0ca3
contract.vault=0x0E7CD8ef9743FEcf94f9103033a044caBD45fC90
contract.router=0xd6A6952545FF6E6E6681c2d15C59f9EB8F40FdBC
contract.reputation=0x423a9904e39537a9997fbaF0f220d79D7d545763
contract.validation=0x92bF63E5C7Ac6980f237a7164Ab413BE226187F1

contract.usdc=0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238
contract.weth=0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9


ai.orchestrator.bar.count = 200
ai.orchestrator.bar.items = 100
ai.orchestrator.bar.duration = 10
ai.orchestrator.bar.warmupms = 5000
ai.orchestrator.confidence = 0.65
ai.orchestrator.atr = 0.01
ai.agent.metadata.uri = ipfs://bafkreih6mti2xb6xtggfslxr3rmnowysiqu3pcrshwxriilydrzke4ilwq
# Agent private key (use one of Hardhat's default accounts)
ai.agent.private-key=0x5e0a8eb2bfde8c1b9ad1d6f75a23a73e7320f9e7b07cdace76aeb479e5b96b6a
ai.agent.id=36

ai.pair = ETHUSD

# Fix for Sepolia Chain ID
eip712.chainId=11155111
eip712.name=RiskRouter


#ai.binance.stream.url = wss://fstream.binance.com/stream?streams=ethusdt@bookTicker/ethusdt@aggTrade/ethusdt@markPrice
ai.binance.stream.url = wss://stream.binance.com:9443/stream?streams=ethusdt@depth10/ethusdt@bookTicker/ethusdt@aggTrade

# trade service params
trade.service.confidence = 0.65
trade.service.allowed_time = 30

#Number of blocks to wait after mining (1 is usually safe for testnets/L2s)
blockchain.confirmations.required=1
# How often to check for new blocks (in milliseconds)
blockchain.polling.interval.ms=2000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

# Python AI service
ai.service.url=http://localhost:5000

logging.file.name=logs/trading-agent.log
logging.level.org.springframework.data.redis=DEBUG
logging.level.io.lettuce.core=DEBUG

# crypto compare key
api.cryptocompare.key = be7649b6b62bf5a408ce18cef062a359930d6257b3992835302cea657c6342a3
api.newsapi.key=82da63e493e04ccf835e57839d5a97dd

